name: Issue Flow
on: [issues, issue_comment]
jobs:
    show-issue:
        runs-on: ubuntu-latest
        steps:
            - name: Show Details
              run: echo "${{ toJson(github) }}"
            - name: Issue Details
              run: echo "${{ toJson(github.event) }}"