name: Practice Workflow
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: npm install
              run: npm install
            - name: dependencies
              run: npm ci
            - name: Lint Script
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Test Script
              run: npm run test
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build Script
              run: npm run build