name: Practice Workflow
on: push
jobs:
    lint-test-build:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: install Node
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: dependencies
              run: npm ci
            - name: Lint Script
              run: npm run lint
            - name: Test Script
              run: npm run test
            - name: Build Script
              run: npm run build