name: Practice Workflow
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Lint Script
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Test Script
              run: npm run test
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Build Script
              run: npm run build